/**
 * Turn docs/research/<host>/content.json into typed data modules under src/data/,
 * downloading any image referenced there that is not in public/ yet.
 * Usage: node scripts/generate-data.mjs
 */
import fs from 'node:fs/promises';
import fss from 'node:fs';
import path from 'node:path';

const HOST = process.env.TARGET_HOST || 'www.bakingo.com';
const RES = path.join('docs', 'research', HOST);
const DATA = path.join('src', 'data');

const slug = (u) =>
  path.basename(new URL(u).pathname).replace(/\.(?=[^.]*\.)/g, '-').replace(/[^a-zA-Z0-9._-]/g, '-').toLowerCase();

const localFor = (u) => {
  if (!u || !u.startsWith('http')) return u || '';
  const host = new URL(u).hostname;
  const dir = /cdninstagram/.test(host) ? 'images/instagram' : 'images';
  return `/${dir}/${slug(u)}`;
};

const ensureLocal = async (u) => {
  if (!u || !u.startsWith('http')) return u || '';
  const rel = localFor(u);
  const file = path.join('public', rel.slice(1));
  if (fss.existsSync(file)) return rel;
  try {
    const res = await fetch(u, { headers: { Referer: `https://${HOST}/` } });
    if (!res.ok) { console.log('  miss', res.status, u.slice(0, 100)); return rel; }
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, Buffer.from(await res.arrayBuffer()));
    console.log('  +', rel);
    return rel;
  } catch (e) {
    console.log('  err', e.message, u.slice(0, 80));
    return rel;
  }
};

const ts = (name, type, value) =>
  `export const ${name}: ${type} = ${JSON.stringify(value, null, 2)};\n`;

const run = async () => {
  const c = JSON.parse(await fs.readFile(path.join(RES, 'content.json'), 'utf8'));
  await fs.mkdir(DATA, { recursive: true });

  // ---------- hero ----------
  const heroReal = c.hero.filter((s) => !s.cloned).slice(0, 5);
  const heroSlides = [];
  for (const s of heroReal) {
    heroSlides.push({ image: await ensureLocal(s.src), alt: s.alt, href: s.href || '#' });
  }

  // ---------- categories ----------
  const categories = [];
  for (const cat of c.categories) {
    categories.push({ label: cat.label, href: cat.href || '#', image: await ensureLocal(cat.img), alt: cat.alt || 'Cake Category' });
  }

  // ---------- products ----------
  const seen = new Set();
  const products = [];
  for (const p of c.products) {
    const key = p.img;
    if (seen.has(key)) continue;
    seen.add(key);
    products.push({
      name: p.name,
      href: p.href || '#',
      image: await ensureLocal(p.img),
      alt: p.alt || p.name,
      // .re-price holds the bare number; the site renders ₹ via a ::before glyph
      price: p.price ? `₹${p.price}` : '',
      rating: p.rating || '',
      // "(8.8K Reviews)" -> "8.8K"
      reviews: (p.reviews || '').replace(/[()]/g, '').replace(/\s*Reviews?$/i, ''),
      eggless: !!p.eggless,
    });
  }

  // ---------- promises ----------
  const promises = [];
  for (const p of c.promises) {
    promises.push({ image: await ensureLocal(p.img), alt: p.alt, title: p.title, body: p.body });
  }

  // ---------- cta ----------
  const cta = { image: await ensureLocal(c.cta.img), alt: c.cta.alt, texts: c.cta.texts, href: c.cta.href || '#' };

  // ---------- social ----------
  const socialRows = [];
  for (const row of c.social.rows) {
    const tiles = [];
    for (const t of row) {
      if (!t.src || !t.src.startsWith('http')) continue;
      tiles.push({ image: await ensureLocal(t.src), alt: t.alt || '', width: t.w, height: t.h });
    }
    socialRows.push(tiles);
  }
  const socialTiles = socialRows.flat();

  // ---------- header ----------
  const headerActions = [];
  for (const a of c.utility.actions) {
    headerActions.push({ label: a.label, href: a.href || '#', icon: await ensureLocal(a.icon), dropdown: a.dropdown });
  }
  const header_ = {
    logo: await ensureLocal(c.utility.logo),
    locationLabel: c.utility.locationLabel,
    searchPlaceholder: c.utility.searchPlaceholder,
    searchIcon: await ensureLocal(c.utility.searchIcon),
    actions: headerActions,
  };

  // ---------- footer socials ----------
  const footerSocials = [];
  for (const s of c.footer.socials) {
    footerSocials.push({ href: s.href || '#', icon: await ensureLocal(s.icon), name: s.cls.replace('footer-', '') });
  }
  const footerLogo = await ensureLocal(c.footer.logo);
  const subscribeArrow = await ensureLocal(c.footer.subscribeArrow);

  const banner = (what, types) =>
    `/**\n * ${what}\n * Extracted verbatim from https://${HOST}/ — generated by scripts/generate-data.mjs.\n */\n` +
    (types.length ? `import type { ${types.join(', ')} } from "@/types/bakingo";\n\n` : '\n');

  const files = {
    'hero.ts': banner('Hero carousel slides.', ['HeroSlide']) + ts('heroSlides', 'HeroSlide[]', heroSlides),
    'categories.ts': banner('Category rail tiles.', ['CategoryTile']) + ts('categoryTiles', 'CategoryTile[]', categories),
    'products.ts':
      banner('India Loves bestseller cards.', ['ProductCard', 'SectionHeading']) +
      ts('bestsellers', 'ProductCard[]', products) +
      '\n' +
      ts('bestsellersHeading', 'SectionHeading', {
        eyebrow: c.bestsellerHeading.eyebrow,
        subtitle: c.bestsellerHeading.subtitle,
      }),
    'promise.ts':
      banner('Our Promise columns.', ['PromiseItem', 'SectionHeading']) +
      ts('promiseItems', 'PromiseItem[]', promises) +
      '\n' +
      ts('promiseHeading', 'SectionHeading', c.promiseHeading),
    'cta.ts': banner('Magical Ticket banner.', ['CtaContent']) + ts('ctaContent', 'CtaContent', cta),
    'social.ts':
      banner("What's In Your Heart social tiles.", ['SocialTile', 'SectionHeading']) +
      ts('socialRows', 'SocialTile[][]', socialRows) +
      '\n' +
      ts('socialTiles', 'SocialTile[]', socialTiles) +
      '\n' +
      ts('socialHeading', 'SectionHeading', { eyebrow: c.social.heading, subtitle: c.social.subHeading }),
    'header.ts':
      banner('Header utility bar + navigation tree.', ['NavItem', 'HeaderContent']) +
      ts('headerContent', 'HeaderContent', header_) +
      '\n' +
      ts('navItems', 'NavItem[]', c.nav),
    'categoriesHeading.ts':
      banner('Category rail heading.', ['SectionHeading']) + ts('categoryHeading', 'SectionHeading', c.categoryHeading),
    'footer.ts':
      banner('Footer content.', ['FooterColumn', 'FooterSocial']) +
      ts('footerColumns', 'FooterColumn[]', c.footer.columns) +
      '\n' +
      ts('footerSocials', 'FooterSocial[]', footerSocials) +
      '\n' +
      ts(
        'footerMeta',
        '{ newsletterHeading: string; inputPlaceholder: string; copyright: string; logo: string; subscribeArrow: string }',
        {
          newsletterHeading: c.footer.newsletterHeading,
          inputPlaceholder: c.footer.inputPlaceholder,
          copyright: c.footer.copyright,
          logo: footerLogo,
          subscribeArrow,
        }
      ),
    'seo.ts':
      banner('SEO sub-footer links + copy.', ['SeoLink']) +
      ts('seoLinks', 'SeoLink[]', c.seo.links) +
      '\n' +
      ts('seoHeading', 'string', c.seo.heading) +
      '\n' +
      ts('seoParagraphs', 'string[]', c.seo.paragraphs),
  };

  for (const [name, body] of Object.entries(files)) {
    await fs.writeFile(path.join(DATA, name), body, 'utf8');
  }
  await fs.rm(path.join(DATA, 'nav.ts'), { force: true });
  console.log('data written:', Object.keys(files).join(', '));
  console.log(`hero=${heroSlides.length} categories=${categories.length} products=${products.length} promises=${promises.length} socialRows=${socialRows.map((r) => r.length).join('/')}`);
};

run().catch((e) => { console.error('FAILED:', e.message); process.exit(1); });
