/**
 * Convert downloaded SVG assets into typed React components in src/components/icons.tsx.
 * Usage: node scripts/generate-icons.mjs
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const SRC = path.join('public', 'images');
const OUT = path.join('src', 'components', 'icons.tsx');

/** file in public/images -> exported component name */
const MAP = {
  'bakingo-logo-re.svg': 'BakingoLogo',
  'bakingo-8d020708.svg': 'BakingoWordmark',
  'search-mob.svg': 'SearchIcon',
  'shopping-cart.svg': 'CartIcon',
  'user-profile.svg': 'UserIcon',
  'track-order.svg': 'TrackOrderIcon',
  'heart-white-0cd76d24.svg': 'HeartIcon',
  'subscribe-arrow-6ada1d89.svg': 'SubscribeArrowIcon',
  'insta-5b618928.svg': 'InstagramIcon',
  'fb-a669391b.svg': 'FacebookIcon',
  'twitter-2c75e3c0.svg': 'TwitterIcon',
  'linked-8efee685.svg': 'LinkedInIcon',
  'yt-49863f07.svg': 'YoutubeIcon',
  'instreel-f142e55b.svg': 'ReelIcon',
  'storyman-fc229179.svg': 'StoryIcon',
};

/** Attributes that must be camelCased for JSX. */
const ATTR = {
  'stroke-width': 'strokeWidth', 'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin', 'stroke-miterlimit': 'strokeMiterlimit',
  'stroke-dasharray': 'strokeDasharray', 'stroke-dashoffset': 'strokeDashoffset',
  'stroke-opacity': 'strokeOpacity', 'fill-rule': 'fillRule', 'fill-opacity': 'fillOpacity',
  'clip-rule': 'clipRule', 'clip-path': 'clipPath', 'mask-type': 'maskType',
  'maskUnits': 'maskUnits', 'gradientUnits': 'gradientUnits', 'xlink:href': 'xlinkHref',
  'stop-color': 'stopColor', 'stop-opacity': 'stopOpacity', 'color-interpolation-filters': 'colorInterpolationFilters',
  'xmlns:xlink': 'xmlnsXlink', 'xml:space': 'xmlSpace', 'baseProfile': 'baseProfile',
  'text-anchor': 'textAnchor', 'font-family': 'fontFamily', 'font-size': 'fontSize',
  'font-weight': 'fontWeight', 'letter-spacing': 'letterSpacing', 'paint-order': 'paintOrder',
  'vector-effect': 'vectorEffect', 'shape-rendering': 'shapeRendering',
};

const toJsx = (svg, suffix) => {
  let s = svg
    .replace(/<\?xml[^>]*\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<!DOCTYPE[^>]*>/gi, '')
    .trim();

  // Namespace ids so multiple icons on one page never collide.
  const ids = [...s.matchAll(/id="([^"]+)"/g)].map((m) => m[1]);
  for (const id of ids) {
    const safe = `${id}_${suffix}`;
    s = s.split(`id="${id}"`).join(`id="${safe}"`);
    s = s.split(`url(#${id})`).join(`url(#${safe})`);
    s = s.split(`href="#${id}"`).join(`href="#${safe}"`);
  }

  // Namespace CSS class names used by embedded <style> blocks, then convert class -> className.
  const classNames = [...s.matchAll(/class="([^"]+)"/g)].flatMap((m) => m[1].split(/\s+/)).filter(Boolean);
  for (const cls of [...new Set(classNames)]) {
    const safe = `${cls}_${suffix}`;
    s = s.split(`.${cls}`).join(`.${safe}`);
    s = s.replace(new RegExp(`class="([^"]*\\b)${cls}(\\b[^"]*)"`, 'g'), (_, a, b) => `class="${a}${safe}${b}"`);
  }
  s = s.replace(/\sclass=/g, ' className=');
  // Embedded <style> bodies contain braces — JSX needs them inside a template literal.
  s = s.replace(/<style>([\s\S]*?)<\/style>/g, (_, css) => `<style>{\`${css.replace(/`/g, '\\`')}\`}</style>`);

  // camelCase attributes
  for (const [k, v] of Object.entries(ATTR)) {
    s = s.replace(new RegExp(`\\s${k}=`, 'g'), ` ${v}=`);
  }
  // inline style="a:b" -> style={{a:'b'}}
  s = s.replace(/style="([^"]*)"/g, (_, css) => {
    const obj = css
      .split(';')
      .filter(Boolean)
      .map((d) => {
        const [p, ...rest] = d.split(':');
        const prop = p.trim().replace(/-([a-z])/g, (_, c) => c.toUpperCase());
        return `${prop}: '${rest.join(':').trim()}'`;
      })
      .join(', ');
    return `style={{ ${obj} }}`;
  });
  // self-close void-ish tags already fine in SVG source; spread props onto <svg>
  s = s.replace(/^<svg /, '<svg {...props} ');
  return s;
};

const run = async () => {
  const parts = [];
  const names = [];
  let i = 0;

  for (const [file, name] of Object.entries(MAP)) {
    const p = path.join(SRC, file);
    let raw;
    try {
      raw = await fs.readFile(p, 'utf8');
    } catch {
      console.log('skip (missing)', file);
      continue;
    }
    const jsx = toJsx(raw, String(i++));
    parts.push(
      `/** ${name} — source: public/images/${file} */\n` +
        `export function ${name}(props: SVGProps<SVGSVGElement>) {\n  return (\n    ${jsx.replace(/\n/g, '\n    ')}\n  );\n}`
    );
    names.push(name);
  }

  const header = `import type { SVGProps } from "react";

/**
 * Icons extracted verbatim from www.bakingo.com.
 * Generated by scripts/generate-icons.mjs — do not hand-edit; re-run the script instead.
 */

`;
  await fs.writeFile(OUT, header + parts.join('\n\n') + '\n', 'utf8');
  console.log('wrote', OUT, '->', names.join(', '));
};

run().catch((e) => { console.error('FAILED:', e.message); process.exit(1); });
