/**
 * Category rail tiles.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-data.mjs.
 */
import type { CategoryTile } from "@/types/bakingo";

export const categoryTiles: CategoryTile[] = [
  {
    "label": "CLASSIC",
    "href": "/cakes",
    "image": "/images/regular-cake.jpg",
    "alt": "Cake Category"
  },
  {
    "label": "Bento",
    "href": "/bento-cakes",
    "image": "/images/bento-cake_1.jpg",
    "alt": "Cake Category"
  },
  {
    "label": "Kids",
    "href": "/cakes/for-kids",
    "image": "/images/kids-theme-cake-20-2-_0.jpg",
    "alt": "Cake Category"
  },
  {
    "label": "GOURMET",
    "href": "/gourmet-cakes",
    "image": "/images/signature.jpg",
    "alt": "Cake Category"
  },
  {
    "label": "PHOTO CAKES",
    "href": "/photo-cakes",
    "image": "/images/photo-20cake_4_2.jpg",
    "alt": "Cake Category"
  },
  {
    "label": "DESIGNER",
    "href": "/designer-cakes",
    "image": "/images/theme-cake-20-2-.jpg",
    "alt": "Cake Category"
  },
  {
    "label": "60 Minutes",
    "href": "/60-minutes-delivery",
    "image": "/images/60min-delivery-20-1-_0.jpg",
    "alt": "Cake Category"
  },
  {
    "label": "Desserts",
    "href": "/all-desserts",
    "image": "/images/dessert-20-2-.jpg",
    "alt": "Cake Category"
  },
  {
    "label": "Hampers",
    "href": "/bakery-baskets",
    "image": "/images/hamper-20-2-.jpg",
    "alt": "Cake Category"
  }
];
