/**
 * Category rail heading.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-data.mjs.
 */
import type { SectionHeading } from "@/types/bakingo";

export const categoryHeading: SectionHeading = {
  "eyebrow": "menu",
  "subtitle": "What will you wish for?"
};
