/**
 * Magical Ticket banner.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-data.mjs.
 */
import type { CtaContent } from "@/types/bakingo";

export const ctaContent: CtaContent = {
  "image": "/images/occ-rem-desktop.png",
  "alt": "promotional banner",
  "texts": [
    "UNLOCK NOW"
  ],
  "href": "#"
};
