/**
 * Footer content.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-data.mjs.
 */
import type { FooterColumn, FooterSocial } from "@/types/bakingo";

export const footerColumns: FooterColumn[] = [
  {
    "heading": "Know Us",
    "links": [
      {
        "label": "Our Story",
        "href": "/about-us"
      },
      {
        "label": "Contact Us",
        "href": "/contact-us"
      },
      {
        "label": "Locate Us",
        "href": "/locate-us"
      },
      {
        "label": "Blog",
        "href": "/blog/"
      },
      {
        "label": "Media",
        "href": "/show-media"
      },
      {
        "label": "Careers",
        "href": "/career-page"
      }
    ]
  },
  {
    "heading": "Need Help",
    "links": [
      {
        "label": "FAQ",
        "href": "/faq"
      },
      {
        "label": "Cancellation and Refund",
        "href": "/cancellation-and-refund-policy"
      },
      {
        "label": "Privacy Policy",
        "href": "/privacy-policy"
      },
      {
        "label": "Terms and Conditions",
        "href": "/terms-and-conditions"
      },
      {
        "label": "Customer Grievance",
        "href": "/customer-grievance-redressal"
      },
      {
        "label": "Sitemap",
        "href": "/sitemap"
      }
    ]
  },
  {
    "heading": "More Info",
    "links": [
      {
        "label": "Corporate Cakes",
        "href": "/corporate-cakes"
      },
      {
        "label": "Coupons & Offers",
        "href": "/coupons-and-offers"
      },
      {
        "label": "Download App",
        "href": "/download-app"
      }
    ]
  }
];

export const footerSocials: FooterSocial[] = [
  {
    "href": "https://www.facebook.com/bakingo/",
    "icon": "/images/fb-a669391b.svg",
    "name": "facebook"
  },
  {
    "href": "https://www.instagram.com/bakingo_official/",
    "icon": "/images/insta-5b618928.svg",
    "name": "instagram"
  },
  {
    "href": "https://twitter.com/bakingo_online/",
    "icon": "/images/twitter-2c75e3c0.svg",
    "name": "twitter"
  },
  {
    "href": "https://www.linkedin.com/company/bakingo/",
    "icon": "/images/linked-8efee685.svg",
    "name": "linkedIn"
  },
  {
    "href": "https://www.youtube.com/channel/UC7MsIUZGOOpVE_vHlklwM4Q",
    "icon": "/images/yt-49863f07.svg",
    "name": "youtube"
  }
];

export const footerMeta: { newsletterHeading: string; inputPlaceholder: string; copyright: string; logo: string; subscribeArrow: string } = {
  "newsletterHeading": "Subscribe To Our Newsletter",
  "inputPlaceholder": "Enter Email Address",
  "copyright": "© 2026. FA GIFTS PVT. LTD.",
  "logo": "/images/bakingo-8d020708.svg",
  "subscribeArrow": "/images/subscribe-arrow-6ada1d89.svg"
};
