/**
 * Header utility bar + navigation tree.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-data.mjs.
 */
import type { NavItem, HeaderContent } from "@/types/bakingo";

export const headerContent: HeaderContent = {
  "logo": "/images/bakingo-logo-re.svg",
  "locationLabel": "Delivering to",
  "searchPlaceholder": "Search for cakes, occasion, flavour and more...",
  "searchIcon": "/images/search_black.png",
  "actions": [
    {
      "label": "Track Order",
      "href": "/trackorder",
      "icon": "/images/track-order.svg",
      "dropdown": []
    },
    {
      "label": "Cart",
      "href": "/cart",
      "icon": "/images/shopping-cart.svg",
      "dropdown": []
    },
    {
      "label": "Login/Signup",
      "href": "#",
      "icon": "/images/user-profile.svg",
      "dropdown": [
        {
          "label": "My Orders",
          "href": "#"
        },
        {
          "label": "My Favourites",
          "href": "#"
        },
        {
          "label": "My Occasions",
          "href": "#"
        },
        {
          "label": "Manage Address",
          "href": "#"
        },
        {
          "label": "My Wallet",
          "href": "#"
        },
        {
          "label": "My Reviews",
          "href": "#"
        },
        {
          "label": "WhatsApp",
          "href": "#"
        },
        {
          "label": "Logout",
          "href": "#"
        }
      ]
    }
  ]
};

export const navItems: NavItem[] = [
  {
    "label": "Cakes",
    "href": null,
    "submenuKind": "submenu-list has-sub-submenu",
    "columns": [
      {
        "heading": "60 Minutes Delivery",
        "links": [
          {
            "label": "60 Minutes Delivery",
            "href": "/60-minutes-delivery"
          },
          {
            "label": "Mango Cakes",
            "href": "/mango-cakes"
          },
          {
            "label": "Fresh Drops",
            "href": "/trending-cakes"
          },
          {
            "label": "Football Cakes",
            "href": "/designer-cakes/football-cakes"
          },
          {
            "label": "Fire Cakes",
            "href": "/designer-cakes/fire-cakes"
          },
          {
            "label": "Bento Cakes",
            "href": "/bento-cakes"
          },
          {
            "label": "Drip Cakes",
            "href": "/drip-cakes"
          },
          {
            "label": "Gourmet Cakes",
            "href": "/gourmet-cakes"
          },
          {
            "label": "Ribbon Cakes",
            "href": "/ribbon-cakes"
          },
          {
            "label": "Anime Cakes",
            "href": "/designer-cakes/anime-cakes"
          }
        ]
      },
      {
        "heading": "Bestsellers",
        "links": [
          {
            "label": "Bestsellers",
            "href": "/best-seller"
          },
          {
            "label": "Eggless Cakes",
            "href": "/eggless-cakes"
          },
          {
            "label": "Photo Cakes",
            "href": "/photo-cakes"
          },
          {
            "label": "Cheese Cakes",
            "href": "/cheesecakes"
          },
          {
            "label": "Half Cakes",
            "href": "/half-cakes"
          },
          {
            "label": "Heart Shaped Cakes",
            "href": "/heart-shape-cakes"
          },
          {
            "label": "Rose Cakes",
            "href": "/rose-cakes"
          },
          {
            "label": "All Cakes",
            "href": "/cakes"
          }
        ]
      },
      {
        "heading": "Chocolate Cakes",
        "links": [
          {
            "label": "Chocolate Cakes",
            "href": "/chocolate-cakes"
          },
          {
            "label": "Pineapple Cakes",
            "href": "/pineapple-cakes"
          },
          {
            "label": "Mango Cakes",
            "href": "/mango-cakes"
          },
          {
            "label": "Fruit Cakes",
            "href": "/fruit-cakes"
          },
          {
            "label": "Butterscotch Cakes",
            "href": "/butterscotch-cakes"
          },
          {
            "label": "Blueberry Cakes",
            "href": "/blueberry-cakes"
          },
          {
            "label": "Black Forest Cakes",
            "href": "/black-forest-cakes"
          },
          {
            "label": "Vanilla Cakes",
            "href": "/vanilla-cakes"
          },
          {
            "label": "Red Velvet Cakes",
            "href": "/red-velvet-cakes"
          },
          {
            "label": "Kit Kat Cakes",
            "href": "/kit-kat-cakes"
          },
          {
            "label": "Oreo Cakes",
            "href": "/oreo-cakes"
          }
        ]
      },
      {
        "heading": "Cakes to Bangalore",
        "links": [
          {
            "label": "Cakes to Bangalore",
            "href": "/cakes/bangalore"
          },
          {
            "label": "Cakes to Delhi",
            "href": "/cakes/delhi"
          },
          {
            "label": "Cakes to Hyderabad",
            "href": "/cakes/hyderabad"
          },
          {
            "label": "Cakes to Mumbai",
            "href": "/cakes/mumbai"
          },
          {
            "label": "Cakes to Noida",
            "href": "/cakes/noida"
          },
          {
            "label": "Cakes to Chennai",
            "href": "/cakes/chennai"
          },
          {
            "label": "Cakes to Gurgaon",
            "href": "/cakes/gurgaon"
          },
          {
            "label": "Cakes to Pune",
            "href": "/cakes/pune"
          },
          {
            "label": "Cakes to Jaipur",
            "href": "/cakes/jaipur"
          },
          {
            "label": "Cakes to Chandigarh",
            "href": "/cakes/chandigarh"
          }
        ]
      }
    ],
    "links": [
      {
        "label": "60 Minutes Delivery",
        "href": "/60-minutes-delivery"
      },
      {
        "label": "Mango Cakes",
        "href": "/mango-cakes"
      },
      {
        "label": "Fresh Drops",
        "href": "/trending-cakes"
      },
      {
        "label": "Football Cakes",
        "href": "/designer-cakes/football-cakes"
      },
      {
        "label": "Fire Cakes",
        "href": "/designer-cakes/fire-cakes"
      },
      {
        "label": "Bento Cakes",
        "href": "/bento-cakes"
      },
      {
        "label": "Drip Cakes",
        "href": "/drip-cakes"
      },
      {
        "label": "Gourmet Cakes",
        "href": "/gourmet-cakes"
      },
      {
        "label": "Ribbon Cakes",
        "href": "/ribbon-cakes"
      },
      {
        "label": "Anime Cakes",
        "href": "/designer-cakes/anime-cakes"
      },
      {
        "label": "Bestsellers",
        "href": "/best-seller"
      },
      {
        "label": "Eggless Cakes",
        "href": "/eggless-cakes"
      },
      {
        "label": "Photo Cakes",
        "href": "/photo-cakes"
      },
      {
        "label": "Cheese Cakes",
        "href": "/cheesecakes"
      },
      {
        "label": "Half Cakes",
        "href": "/half-cakes"
      },
      {
        "label": "Heart Shaped Cakes",
        "href": "/heart-shape-cakes"
      },
      {
        "label": "Rose Cakes",
        "href": "/rose-cakes"
      },
      {
        "label": "All Cakes",
        "href": "/cakes"
      },
      {
        "label": "Chocolate Cakes",
        "href": "/chocolate-cakes"
      },
      {
        "label": "Pineapple Cakes",
        "href": "/pineapple-cakes"
      },
      {
        "label": "Mango Cakes",
        "href": "/mango-cakes"
      },
      {
        "label": "Fruit Cakes",
        "href": "/fruit-cakes"
      },
      {
        "label": "Butterscotch Cakes",
        "href": "/butterscotch-cakes"
      },
      {
        "label": "Blueberry Cakes",
        "href": "/blueberry-cakes"
      },
      {
        "label": "Black Forest Cakes",
        "href": "/black-forest-cakes"
      },
      {
        "label": "Vanilla Cakes",
        "href": "/vanilla-cakes"
      },
      {
        "label": "Red Velvet Cakes",
        "href": "/red-velvet-cakes"
      },
      {
        "label": "Kit Kat Cakes",
        "href": "/kit-kat-cakes"
      },
      {
        "label": "Oreo Cakes",
        "href": "/oreo-cakes"
      },
      {
        "label": "Cakes to Bangalore",
        "href": "/cakes/bangalore"
      },
      {
        "label": "Cakes to Delhi",
        "href": "/cakes/delhi"
      },
      {
        "label": "Cakes to Hyderabad",
        "href": "/cakes/hyderabad"
      },
      {
        "label": "Cakes to Mumbai",
        "href": "/cakes/mumbai"
      },
      {
        "label": "Cakes to Noida",
        "href": "/cakes/noida"
      },
      {
        "label": "Cakes to Chennai",
        "href": "/cakes/chennai"
      },
      {
        "label": "Cakes to Gurgaon",
        "href": "/cakes/gurgaon"
      },
      {
        "label": "Cakes to Pune",
        "href": "/cakes/pune"
      },
      {
        "label": "Cakes to Jaipur",
        "href": "/cakes/jaipur"
      },
      {
        "label": "Cakes to Chandigarh",
        "href": "/cakes/chandigarh"
      }
    ]
  },
  {
    "label": "Bento",
    "href": null,
    "submenuKind": "submenu-list no-sub-menu",
    "columns": [
      {
        "heading": "Love",
        "links": [
          {
            "label": "Love",
            "href": "/love-bento-cakes"
          },
          {
            "label": "Birthday",
            "href": "/birthday-bento-cakes"
          },
          {
            "label": "Anniversary",
            "href": "/anniversary-bento-cakes"
          },
          {
            "label": "Mom",
            "href": "/mom-bento-cakes"
          },
          {
            "label": "Meme",
            "href": "/meme-bento-cakes"
          },
          {
            "label": "Cute",
            "href": "/cute-bento-cakes"
          },
          {
            "label": "Brother",
            "href": "/brother-bento-cakes"
          },
          {
            "label": "Friend",
            "href": "/bento-cakes/for-friend"
          },
          {
            "label": "Husband",
            "href": "/bento-cakes/for-husband"
          },
          {
            "label": "Wife",
            "href": "/bento-cakes/for-wife"
          },
          {
            "label": "Finance",
            "href": "/finance-bento-cakes"
          },
          {
            "label": "Horoscope",
            "href": "/horoscope-bento-cakes"
          },
          {
            "label": "Girlfriend",
            "href": "/bento-cakes/for-girlfriend"
          },
          {
            "label": "All Bento",
            "href": "/bento-cakes"
          },
          {
            "label": "60 Minutes Delivery",
            "href": "/60-minutes-delivery"
          }
        ]
      }
    ],
    "links": [
      {
        "label": "Love",
        "href": "/love-bento-cakes"
      },
      {
        "label": "Birthday",
        "href": "/birthday-bento-cakes"
      },
      {
        "label": "Anniversary",
        "href": "/anniversary-bento-cakes"
      },
      {
        "label": "Mom",
        "href": "/mom-bento-cakes"
      },
      {
        "label": "Meme",
        "href": "/meme-bento-cakes"
      },
      {
        "label": "Cute",
        "href": "/cute-bento-cakes"
      },
      {
        "label": "Brother",
        "href": "/brother-bento-cakes"
      },
      {
        "label": "Friend",
        "href": "/bento-cakes/for-friend"
      },
      {
        "label": "Husband",
        "href": "/bento-cakes/for-husband"
      },
      {
        "label": "Wife",
        "href": "/bento-cakes/for-wife"
      },
      {
        "label": "Finance",
        "href": "/finance-bento-cakes"
      },
      {
        "label": "Horoscope",
        "href": "/horoscope-bento-cakes"
      },
      {
        "label": "Girlfriend",
        "href": "/bento-cakes/for-girlfriend"
      },
      {
        "label": "All Bento",
        "href": "/bento-cakes"
      },
      {
        "label": "60 Minutes Delivery",
        "href": "/60-minutes-delivery"
      }
    ]
  },
  {
    "label": "Theme Cakes",
    "href": null,
    "submenuKind": "submenu-list has-sub-submenu",
    "columns": [
      {
        "heading": "1st Birthday Cakes",
        "links": [
          {
            "label": "1st Birthday Cakes",
            "href": "/1st-birthday-cakes"
          },
          {
            "label": "Princess Cakes",
            "href": "/designer-cakes/princess-cakes"
          },
          {
            "label": "Animal Cakes",
            "href": "/designer-cakes/animal-cakes"
          },
          {
            "label": "Cakes For Boys",
            "href": "/cakes/for-boy"
          },
          {
            "label": "Cakes For Girls",
            "href": "/cakes/for-girl"
          },
          {
            "label": "Number Cakes",
            "href": "/designer-cakes/number-cakes"
          },
          {
            "label": "Alphabet Cakes",
            "href": "/designer-cakes/alphabet-cakes"
          },
          {
            "label": "Car and Vehicle Cakes",
            "href": "/designer-cakes/car-cakes"
          },
          {
            "label": "Baby Shark Cakes",
            "href": "/designer-cakes/baby-shark-cakes"
          },
          {
            "label": "Thomas and Friends Cakes",
            "href": "/designer-cakes/thomas-and-friends-cakes"
          },
          {
            "label": "Winnie the Pooh Cakes",
            "href": "/designer-cakes/winnie-the-pooh-cakes"
          },
          {
            "label": "All Kids Cakes",
            "href": "/cakes/for-kids"
          }
        ]
      },
      {
        "heading": "Spiderman Cakes",
        "links": [
          {
            "label": "Spiderman Cakes",
            "href": "/designer-cakes/spiderman-cakes"
          },
          {
            "label": "Unicorn Cakes",
            "href": "/designer-cakes/unicorn-cakes"
          },
          {
            "label": "Barbie Cakes",
            "href": "/designer-cakes/barbie-cakes"
          },
          {
            "label": "Avenger Cakes",
            "href": "/designer-cakes/avenger-cakes"
          },
          {
            "label": "Peppa Pig Cakes",
            "href": "/designer-cakes/peppa-pig-cakes"
          },
          {
            "label": "Doraemon Cakes",
            "href": "/designer-cakes/doraemon-cakes"
          },
          {
            "label": "Naruto Cakes",
            "href": "/designer-cakes/naruto-cakes"
          },
          {
            "label": "Cocomelon Cakes",
            "href": "/designer-cakes/cocomelon-cakes"
          },
          {
            "label": "Cartoon Cakes",
            "href": "/designer-cakes/cartoon-cakes"
          },
          {
            "label": "Super Hero Cakes",
            "href": "/designer-cakes/superhero-cakes"
          },
          {
            "label": "Bluey Cakes",
            "href": "/designer-cakes/bluey-cakes"
          },
          {
            "label": "Bike Cakes",
            "href": "/designer-cakes/bike-cakes"
          },
          {
            "label": "Iron-Man Cakes",
            "href": "/designer-cakes/iron-man-cakes"
          },
          {
            "label": "Moana Cakes",
            "href": "/designer-cakes/moana-cakes"
          },
          {
            "label": "Train Cakes",
            "href": "/designer-cakes/train-cakes"
          },
          {
            "label": "Transformers Cakes",
            "href": "/designer-cakes/transformers-cakes"
          },
          {
            "label": "Dragon Ball Cakes",
            "href": "/designer-cakes/dragon-ball-cakes"
          },
          {
            "label": "Panda Cakes",
            "href": "/designer-cakes/panda-cakes"
          },
          {
            "label": "Fish Cakes",
            "href": "/designer-cakes/fish-cakes"
          },
          {
            "label": "Ben 10 Cakes",
            "href": "/designer-cakes/ben-10-cakes"
          },
          {
            "label": "Demon Slayer Cakes",
            "href": "/designer-cakes/demon-slayer-cakes"
          },
          {
            "label": "Bubu Dudu Cakes",
            "href": "/designer-cakes/bubu-dudu-cakes"
          },
          {
            "label": "Pony Cakes",
            "href": "/designer-cakes/pony-cakes"
          }
        ]
      },
      {
        "heading": "Makeup Cakes",
        "links": [
          {
            "label": "Makeup Cakes",
            "href": "/designer-cakes/makeup-cakes"
          },
          {
            "label": "Bride To Be Cakes",
            "href": "/designer-cakes/bride-to-be-cakes"
          },
          {
            "label": "Wedding Cakes",
            "href": "/wedding-cakes"
          },
          {
            "label": "Gym Cakes",
            "href": "/designer-cakes/gym-cakes"
          },
          {
            "label": "Party Cakes",
            "href": "/party-cakes"
          },
          {
            "label": "BTS Cakes",
            "href": "/designer-cakes/bts-cakes"
          },
          {
            "label": "Police Cakes",
            "href": "/designer-cakes/police-cakes"
          },
          {
            "label": "Army Cakes",
            "href": "/designer-cakes/army-cakes"
          },
          {
            "label": "Beer Cakes",
            "href": "/designer-cakes/beer-cakes"
          },
          {
            "label": "Bachelor Cakes",
            "href": "/designer-cakes/bachelor-cakes"
          },
          {
            "label": "Ca Cakes",
            "href": "/designer-cakes/ca-cakes"
          },
          {
            "label": "Guitar Cakes",
            "href": "/designer-cakes/guitar-cakes"
          },
          {
            "label": "Aeorplane Cakes",
            "href": "/designer-cakes/aeroplane-cakes"
          }
        ]
      },
      {
        "heading": "Jungle Theme Cakes",
        "links": [
          {
            "label": "Jungle Theme Cakes",
            "href": "/designer-cakes/jungle-theme-cakes"
          },
          {
            "label": "Cricket Cakes",
            "href": "/designer-cakes/cricket-cakes"
          },
          {
            "label": "Football Cakes",
            "href": "/designer-cakes/football-cakes"
          },
          {
            "label": "Basketball Cakes",
            "href": "/designer-cakes/basketball-cakes"
          },
          {
            "label": "Rainbow Cakes",
            "href": "/designer-cakes/rainbow-cakes"
          },
          {
            "label": "Butterfly Cakes",
            "href": "/designer-cakes/butterfly-cakes"
          },
          {
            "label": "Shinchan Cakes",
            "href": "/designer-cakes/shinchan-cakes"
          },
          {
            "label": "Dinosaur Cakes",
            "href": "/designer-cakes/dinosaur-cakes"
          },
          {
            "label": "Pikachu Cakes",
            "href": "/designer-cakes/pikachu-cakes"
          },
          {
            "label": "Hulk Cakes",
            "href": "/designer-cakes/hulk-cakes"
          },
          {
            "label": "Jungle Book Cakes",
            "href": "/designer-cakes/jungle-book-cakes"
          },
          {
            "label": "All Designer Cakes",
            "href": "/designer-cakes"
          }
        ]
      }
    ],
    "links": [
      {
        "label": "1st Birthday Cakes",
        "href": "/1st-birthday-cakes"
      },
      {
        "label": "Princess Cakes",
        "href": "/designer-cakes/princess-cakes"
      },
      {
        "label": "Animal Cakes",
        "href": "/designer-cakes/animal-cakes"
      },
      {
        "label": "Cakes For Boys",
        "href": "/cakes/for-boy"
      },
      {
        "label": "Cakes For Girls",
        "href": "/cakes/for-girl"
      },
      {
        "label": "Number Cakes",
        "href": "/designer-cakes/number-cakes"
      },
      {
        "label": "Alphabet Cakes",
        "href": "/designer-cakes/alphabet-cakes"
      },
      {
        "label": "Car and Vehicle Cakes",
        "href": "/designer-cakes/car-cakes"
      },
      {
        "label": "Baby Shark Cakes",
        "href": "/designer-cakes/baby-shark-cakes"
      },
      {
        "label": "Thomas and Friends Cakes",
        "href": "/designer-cakes/thomas-and-friends-cakes"
      },
      {
        "label": "Winnie the Pooh Cakes",
        "href": "/designer-cakes/winnie-the-pooh-cakes"
      },
      {
        "label": "All Kids Cakes",
        "href": "/cakes/for-kids"
      },
      {
        "label": "Spiderman Cakes",
        "href": "/designer-cakes/spiderman-cakes"
      },
      {
        "label": "Unicorn Cakes",
        "href": "/designer-cakes/unicorn-cakes"
      },
      {
        "label": "Barbie Cakes",
        "href": "/designer-cakes/barbie-cakes"
      },
      {
        "label": "Avenger Cakes",
        "href": "/designer-cakes/avenger-cakes"
      },
      {
        "label": "Peppa Pig Cakes",
        "href": "/designer-cakes/peppa-pig-cakes"
      },
      {
        "label": "Doraemon Cakes",
        "href": "/designer-cakes/doraemon-cakes"
      },
      {
        "label": "Naruto Cakes",
        "href": "/designer-cakes/naruto-cakes"
      },
      {
        "label": "Cocomelon Cakes",
        "href": "/designer-cakes/cocomelon-cakes"
      },
      {
        "label": "Cartoon Cakes",
        "href": "/designer-cakes/cartoon-cakes"
      },
      {
        "label": "Super Hero Cakes",
        "href": "/designer-cakes/superhero-cakes"
      },
      {
        "label": "Bluey Cakes",
        "href": "/designer-cakes/bluey-cakes"
      },
      {
        "label": "Bike Cakes",
        "href": "/designer-cakes/bike-cakes"
      },
      {
        "label": "Iron-Man Cakes",
        "href": "/designer-cakes/iron-man-cakes"
      },
      {
        "label": "Moana Cakes",
        "href": "/designer-cakes/moana-cakes"
      },
      {
        "label": "Train Cakes",
        "href": "/designer-cakes/train-cakes"
      },
      {
        "label": "Transformers Cakes",
        "href": "/designer-cakes/transformers-cakes"
      },
      {
        "label": "Dragon Ball Cakes",
        "href": "/designer-cakes/dragon-ball-cakes"
      },
      {
        "label": "Panda Cakes",
        "href": "/designer-cakes/panda-cakes"
      },
      {
        "label": "Fish Cakes",
        "href": "/designer-cakes/fish-cakes"
      },
      {
        "label": "Ben 10 Cakes",
        "href": "/designer-cakes/ben-10-cakes"
      },
      {
        "label": "Demon Slayer Cakes",
        "href": "/designer-cakes/demon-slayer-cakes"
      },
      {
        "label": "Bubu Dudu Cakes",
        "href": "/designer-cakes/bubu-dudu-cakes"
      },
      {
        "label": "Pony Cakes",
        "href": "/designer-cakes/pony-cakes"
      },
      {
        "label": "Makeup Cakes",
        "href": "/designer-cakes/makeup-cakes"
      },
      {
        "label": "Bride To Be Cakes",
        "href": "/designer-cakes/bride-to-be-cakes"
      },
      {
        "label": "Wedding Cakes",
        "href": "/wedding-cakes"
      },
      {
        "label": "Gym Cakes",
        "href": "/designer-cakes/gym-cakes"
      },
      {
        "label": "Party Cakes",
        "href": "/party-cakes"
      },
      {
        "label": "BTS Cakes",
        "href": "/designer-cakes/bts-cakes"
      },
      {
        "label": "Police Cakes",
        "href": "/designer-cakes/police-cakes"
      },
      {
        "label": "Army Cakes",
        "href": "/designer-cakes/army-cakes"
      },
      {
        "label": "Beer Cakes",
        "href": "/designer-cakes/beer-cakes"
      },
      {
        "label": "Bachelor Cakes",
        "href": "/designer-cakes/bachelor-cakes"
      },
      {
        "label": "Ca Cakes",
        "href": "/designer-cakes/ca-cakes"
      },
      {
        "label": "Guitar Cakes",
        "href": "/designer-cakes/guitar-cakes"
      },
      {
        "label": "Aeorplane Cakes",
        "href": "/designer-cakes/aeroplane-cakes"
      },
      {
        "label": "Jungle Theme Cakes",
        "href": "/designer-cakes/jungle-theme-cakes"
      },
      {
        "label": "Cricket Cakes",
        "href": "/designer-cakes/cricket-cakes"
      },
      {
        "label": "Football Cakes",
        "href": "/designer-cakes/football-cakes"
      },
      {
        "label": "Basketball Cakes",
        "href": "/designer-cakes/basketball-cakes"
      },
      {
        "label": "Rainbow Cakes",
        "href": "/designer-cakes/rainbow-cakes"
      },
      {
        "label": "Butterfly Cakes",
        "href": "/designer-cakes/butterfly-cakes"
      },
      {
        "label": "Shinchan Cakes",
        "href": "/designer-cakes/shinchan-cakes"
      },
      {
        "label": "Dinosaur Cakes",
        "href": "/designer-cakes/dinosaur-cakes"
      },
      {
        "label": "Pikachu Cakes",
        "href": "/designer-cakes/pikachu-cakes"
      },
      {
        "label": "Hulk Cakes",
        "href": "/designer-cakes/hulk-cakes"
      },
      {
        "label": "Jungle Book Cakes",
        "href": "/designer-cakes/jungle-book-cakes"
      },
      {
        "label": "All Designer Cakes",
        "href": "/designer-cakes"
      }
    ]
  },
  {
    "label": "By Relationship",
    "href": null,
    "submenuKind": "submenu-list has-sub-submenu",
    "columns": [
      {
        "heading": "Cakes for Husband",
        "links": [
          {
            "label": "Cakes for Husband",
            "href": "/cakes/for-husband"
          },
          {
            "label": "Cakes For Boyfriend",
            "href": "/cakes/for-boyfriend"
          },
          {
            "label": "Cakes for Father",
            "href": "/cakes/for-father"
          },
          {
            "label": "Cakes for Brother",
            "href": "/cakes/for-brother"
          },
          {
            "label": "Cakes For Son",
            "href": "/cakes/for-son"
          }
        ]
      },
      {
        "heading": "Cakes for Wife",
        "links": [
          {
            "label": "Cakes for Wife",
            "href": "/cakes/for-wife"
          },
          {
            "label": "Cakes for Mother",
            "href": "/cakes/for-mother"
          },
          {
            "label": "Cakes For Girlfriend",
            "href": "/cakes/for-girlfriend"
          },
          {
            "label": "Cakes for Sister",
            "href": "/cakes/for-sister"
          },
          {
            "label": "Cakes For Daughter",
            "href": "/cakes/for-daughter"
          }
        ]
      }
    ],
    "links": [
      {
        "label": "Cakes for Husband",
        "href": "/cakes/for-husband"
      },
      {
        "label": "Cakes For Boyfriend",
        "href": "/cakes/for-boyfriend"
      },
      {
        "label": "Cakes for Father",
        "href": "/cakes/for-father"
      },
      {
        "label": "Cakes for Brother",
        "href": "/cakes/for-brother"
      },
      {
        "label": "Cakes For Son",
        "href": "/cakes/for-son"
      },
      {
        "label": "Cakes for Wife",
        "href": "/cakes/for-wife"
      },
      {
        "label": "Cakes for Mother",
        "href": "/cakes/for-mother"
      },
      {
        "label": "Cakes For Girlfriend",
        "href": "/cakes/for-girlfriend"
      },
      {
        "label": "Cakes for Sister",
        "href": "/cakes/for-sister"
      },
      {
        "label": "Cakes For Daughter",
        "href": "/cakes/for-daughter"
      }
    ]
  },
  {
    "label": "Desserts & Hampers",
    "href": null,
    "submenuKind": "submenu-list has-sub-submenu",
    "columns": [
      {
        "heading": "All Desserts",
        "links": [
          {
            "label": "All Desserts",
            "href": "/all-desserts"
          },
          {
            "label": "Jar Cakes",
            "href": "/jar-cakes"
          },
          {
            "label": "Pastries",
            "href": "/pastries"
          },
          {
            "label": "Cheese Cakes",
            "href": "/cheesecakes"
          },
          {
            "label": "Cup Cakes",
            "href": "/cup-cakes"
          },
          {
            "label": "Brownies",
            "href": "/brownies"
          },
          {
            "label": "Cookies",
            "href": "/cookies"
          },
          {
            "label": "Tea Cakes",
            "href": "/tea-cakes"
          },
          {
            "label": "60 Minutes Delivery",
            "href": "/60-minutes-delivery"
          }
        ]
      },
      {
        "heading": "Bakery Basket",
        "links": [
          {
            "label": "Bakery Basket",
            "href": "/bakery-baskets"
          },
          {
            "label": "Make Your Own Hamper",
            "href": "/p/bakery-baskets/make-your-own-hamper-hamp4315"
          },
          {
            "label": "Assorted Pastry Box",
            "href": "/p/bakery-baskets/assorted-desserts-box-hamp4496assorted"
          },
          {
            "label": "Cupcake Delight Box",
            "href": "/p/cupcake/assorted-cup-cakes-cup4634assorted"
          },
          {
            "label": "Make Your Dessert Box",
            "href": "/p/bakery-baskets/mixed-magic-dessert-box-hamp4694assorted"
          },
          {
            "label": "Gift Hampers",
            "href": "/gift-hampers"
          }
        ]
      }
    ],
    "links": [
      {
        "label": "All Desserts",
        "href": "/all-desserts"
      },
      {
        "label": "Jar Cakes",
        "href": "/jar-cakes"
      },
      {
        "label": "Pastries",
        "href": "/pastries"
      },
      {
        "label": "Cheese Cakes",
        "href": "/cheesecakes"
      },
      {
        "label": "Cup Cakes",
        "href": "/cup-cakes"
      },
      {
        "label": "Brownies",
        "href": "/brownies"
      },
      {
        "label": "Cookies",
        "href": "/cookies"
      },
      {
        "label": "Tea Cakes",
        "href": "/tea-cakes"
      },
      {
        "label": "60 Minutes Delivery",
        "href": "/60-minutes-delivery"
      },
      {
        "label": "Bakery Basket",
        "href": "/bakery-baskets"
      },
      {
        "label": "Make Your Own Hamper",
        "href": "/p/bakery-baskets/make-your-own-hamper-hamp4315"
      },
      {
        "label": "Assorted Pastry Box",
        "href": "/p/bakery-baskets/assorted-desserts-box-hamp4496assorted"
      },
      {
        "label": "Cupcake Delight Box",
        "href": "/p/cupcake/assorted-cup-cakes-cup4634assorted"
      },
      {
        "label": "Make Your Dessert Box",
        "href": "/p/bakery-baskets/mixed-magic-dessert-box-hamp4694assorted"
      },
      {
        "label": "Gift Hampers",
        "href": "/gift-hampers"
      }
    ]
  },
  {
    "label": "Birthday",
    "href": null,
    "submenuKind": "submenu-list no-sub-menu",
    "columns": [
      {
        "heading": "Birthday Cakes",
        "links": [
          {
            "label": "Birthday Cakes",
            "href": "/birthday-cakes"
          },
          {
            "label": "Birthday Photo Cakes",
            "href": "/birthday-photo-cakes"
          },
          {
            "label": "Half Birthday Cakes",
            "href": "/half-cakes"
          },
          {
            "label": "1st Birthday Cakes",
            "href": "/1st-birthday-cakes"
          },
          {
            "label": "2nd Birthday Cakes",
            "href": "/2nd-birthday-cakes"
          },
          {
            "label": "18th Birthday Cakes",
            "href": "/18th-birthday-cakes"
          },
          {
            "label": "40th Birthday Cakes",
            "href": "/40th-birthday-cakes"
          },
          {
            "label": "50th Birthday Cakes",
            "href": "/50th-birthday-cakes"
          },
          {
            "label": "60 Minutes Delivery",
            "href": "/60-minutes-delivery"
          }
        ]
      }
    ],
    "links": [
      {
        "label": "Birthday Cakes",
        "href": "/birthday-cakes"
      },
      {
        "label": "Birthday Photo Cakes",
        "href": "/birthday-photo-cakes"
      },
      {
        "label": "Half Birthday Cakes",
        "href": "/half-cakes"
      },
      {
        "label": "1st Birthday Cakes",
        "href": "/1st-birthday-cakes"
      },
      {
        "label": "2nd Birthday Cakes",
        "href": "/2nd-birthday-cakes"
      },
      {
        "label": "18th Birthday Cakes",
        "href": "/18th-birthday-cakes"
      },
      {
        "label": "40th Birthday Cakes",
        "href": "/40th-birthday-cakes"
      },
      {
        "label": "50th Birthday Cakes",
        "href": "/50th-birthday-cakes"
      },
      {
        "label": "60 Minutes Delivery",
        "href": "/60-minutes-delivery"
      }
    ]
  },
  {
    "label": "Anniversary",
    "href": null,
    "submenuKind": "submenu-list no-sub-menu",
    "columns": [
      {
        "heading": "All Anniversary Cakes",
        "links": [
          {
            "label": "All Anniversary Cakes",
            "href": "/anniversary-cakes"
          },
          {
            "label": "Anniversary Photo Cakes",
            "href": "/anniversary-photo-cakes"
          },
          {
            "label": "Anniversary Cakes For Parents",
            "href": "/anniversary-cakes-for-parents"
          },
          {
            "label": "1st Anniversary Cakes",
            "href": "/1st-anniversary-cakes"
          },
          {
            "label": "25th Anniversary Cakes",
            "href": "/25th-anniversary-cakes"
          },
          {
            "label": "5th Anniversary Cakes",
            "href": "/5th-anniversary-cakes"
          },
          {
            "label": "10th Anniversary Cakes",
            "href": "/10th-anniversary-cakes"
          },
          {
            "label": "50th Anniversary Cakes",
            "href": "/50th-anniversary-cakes"
          }
        ]
      }
    ],
    "links": [
      {
        "label": "All Anniversary Cakes",
        "href": "/anniversary-cakes"
      },
      {
        "label": "Anniversary Photo Cakes",
        "href": "/anniversary-photo-cakes"
      },
      {
        "label": "Anniversary Cakes For Parents",
        "href": "/anniversary-cakes-for-parents"
      },
      {
        "label": "1st Anniversary Cakes",
        "href": "/1st-anniversary-cakes"
      },
      {
        "label": "25th Anniversary Cakes",
        "href": "/25th-anniversary-cakes"
      },
      {
        "label": "5th Anniversary Cakes",
        "href": "/5th-anniversary-cakes"
      },
      {
        "label": "10th Anniversary Cakes",
        "href": "/10th-anniversary-cakes"
      },
      {
        "label": "50th Anniversary Cakes",
        "href": "/50th-anniversary-cakes"
      }
    ]
  },
  {
    "label": "Occasions",
    "href": null,
    "submenuKind": "submenu-list has-sub-submenu",
    "columns": [
      {
        "heading": "Independence Day Cakes",
        "links": [
          {
            "label": "Independence Day Cakes",
            "href": "/independence-day-cakes"
          },
          {
            "label": "Rakhi Cakes",
            "href": "/rakhi-with-cakes"
          },
          {
            "label": "Janmashtami Cakes",
            "href": "/janmashtami-cakes"
          }
        ]
      },
      {
        "heading": "Baby Shower Cakes",
        "links": [
          {
            "label": "Baby Shower Cakes",
            "href": "/designer-cakes/baby-shower-cakes"
          },
          {
            "label": "Congratulations Cakes",
            "href": "/congratulations-cakes"
          },
          {
            "label": "Retirement Cakes",
            "href": "/retirement-cakes"
          },
          {
            "label": "Farewell Cakes",
            "href": "/farewell-cakes"
          },
          {
            "label": "Wedding Cakes",
            "href": "/wedding-cakes"
          }
        ]
      }
    ],
    "links": [
      {
        "label": "Independence Day Cakes",
        "href": "/independence-day-cakes"
      },
      {
        "label": "Rakhi Cakes",
        "href": "/rakhi-with-cakes"
      },
      {
        "label": "Janmashtami Cakes",
        "href": "/janmashtami-cakes"
      },
      {
        "label": "Baby Shower Cakes",
        "href": "/designer-cakes/baby-shower-cakes"
      },
      {
        "label": "Congratulations Cakes",
        "href": "/congratulations-cakes"
      },
      {
        "label": "Retirement Cakes",
        "href": "/retirement-cakes"
      },
      {
        "label": "Farewell Cakes",
        "href": "/farewell-cakes"
      },
      {
        "label": "Wedding Cakes",
        "href": "/wedding-cakes"
      }
    ]
  },
  {
    "label": "Customized Cakes",
    "href": "/customised-cakes",
    "submenuKind": "",
    "columns": [],
    "links": []
  }
];
