/**
 * Hero carousel slides.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-data.mjs.
 */
import type { HeroSlide } from "@/types/bakingo";

export const heroSlides: HeroSlide[] = [
  {
    "image": "/images/anniversary-desktop_0.png",
    "alt": "Anniversary Cakes",
    "href": "/anniversary-cakes"
  },
  {
    "image": "/images/gaourmet-banner-web_desktop-banner_1.png",
    "alt": "Gourmet Cakes",
    "href": "/gourmet-collection"
  },
  {
    "image": "/images/3668x1714-theme-cake-20-2-.png",
    "alt": "Theme Cakes",
    "href": "/designer-cakes"
  },
  {
    "image": "/images/banner-birthday-web.png",
    "alt": "Birthday Cakes",
    "href": "/birthday-cakes"
  },
  {
    "image": "/images/regular-cake-desktop-20-1-.png",
    "alt": "Regular Cakes",
    "href": "/cakes"
  }
];
