/**
 * The /best-seller listing page: title, filter chips, review strip, quick links.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-catalog.mjs.
 */
import type { ListingChip, QuickLinkGroup, NavLink } from "@/types/bakingo";

export const listingTitle: string = "Best Sellers";

export const listingChips: ListingChip[] = [
  {
    "label": "Pineapple"
  },
  {
    "label": "Butterscotch"
  },
  {
    "label": "Fruit"
  },
  {
    "label": "Chocolate"
  },
  {
    "label": "Red velvet"
  },
  {
    "label": "60 Minute Delivery"
  }
];

export const listingSortLabel: string = "Sort";

export const listingBreadcrumbs: NavLink[] = [
  {
    "label": "Home",
    "href": "/"
  },
  {
    "label": "Best Seller",
    "href": null
  }
];

export const listingSeoHeading: string = "Best Selling Products of Bakingo";

export const listingSeoParagraphs: string[] = [
  "Bakingo is a reputed online bakery providing services in seven metro Indian cities of Bangalore, Hyderabad, Secunderabad, Delhi, Ghaziabad, Noida, and Gurgaon. So, it comes as no surprise that cakes and desserts top the list of best selling products. Ranging from designer cakes to jar cakes to photo cakes to cupcakes to heart-shaped cakes, we have countless cake options in the category of best seller desserts. We provide the delivery of best-selling cakes across several occasions like birthdays, anniversaries, Valentine’s Day, success parties, festivities, etc. So, why settle for less when you can have and treat your relatives with the best? Steal the heart of your partner by making him or her relish heartilicious heart-shaped cakes on the anniversary, Valentine’s Day, etc. that is most favoured by our thick base of customers. You can delight your little minion by sending him or her a cake on his or her birthday from the best-selling birthday cakes available at Bakingo. Keep scrolling until you find yours!",
  "Bakingo is the bakery selling the best desserts to the ones born with sweet-tooth, online. A user-friendly experience awaits you at Bakingo.com. When you visit us to order bestselling anniversary cakes or bestseller cakes for any event, you will experience that cake shopping on Bakingo is smooth and seamless. Within a few clicks, you can order a cake for either yourself or your relatives. You can do all this without compromising on your comfort and convenience. Isn’t this amazing? And, very soon, Bakingo will be coming up with its mobile app that will take your experience to another level. Excited? Well, we are as much as you! Bakingo also provides online delivery options for best-selling cakes and desserts, so that you do not have to worry about its dispatch. Bakingo takes care of everything!",
  "Bakingo provides three-delivery options, i.e., same-day, midnight, and instant. Our delivery services are prompt and timely across all the seven Indian cities. If you go with our instant delivery of valentine cakes, the cake will reach the designated doorstep within three hours of the order placed. Midnight delivery guarantees the arrival of the cake at midnight. If you choose the same-day delivery, Bakingo will deliver the cake on the selected date and time."
];

export const quickLinksHeading: string = "Quick Links";

export const quickLinkGroups: QuickLinkGroup[] = [
  {
    "heading": "TOP CAKE DELIVERY CITIES",
    "links": [
      {
        "label": "Delhi",
        "href": "/cakes/delhi"
      },
      {
        "label": "Bangalore",
        "href": "/cakes/bangalore"
      },
      {
        "label": "Gurgaon",
        "href": "/cakes/gurgaon"
      },
      {
        "label": "Noida",
        "href": "/cakes/noida"
      },
      {
        "label": "Ghaziabad",
        "href": "/cakes/ghaziabad"
      },
      {
        "label": "Hyderabad",
        "href": "/cakes/hyderabad"
      },
      {
        "label": "Kolkata",
        "href": "/cakes/kolkata"
      },
      {
        "label": "Chennai",
        "href": "/cakes/chennai"
      },
      {
        "label": "Mumbai",
        "href": "/cakes/mumbai"
      },
      {
        "label": "Pune",
        "href": "/cakes/pune"
      },
      {
        "label": "Secunderabad",
        "href": "/cakes/secunderabad"
      },
      {
        "label": "Coimbatore",
        "href": "/cakes/coimbatore"
      },
      {
        "label": "Kanpur",
        "href": "/cakes/kanpur"
      },
      {
        "label": "Jaipur",
        "href": "/cakes/jaipur"
      },
      {
        "label": "Faridabad",
        "href": "/cakes/faridabad"
      },
      {
        "label": "Ahmedabad",
        "href": "/cakes/ahmedabad"
      },
      {
        "label": "Lucknow",
        "href": "/cakes/lucknow"
      },
      {
        "label": "Ranchi",
        "href": "/cakes/ranchi"
      },
      {
        "label": "Ludhiana",
        "href": "/cakes/ludhiana"
      },
      {
        "label": "Chandigarh",
        "href": "/cakes/chandigarh"
      }
    ]
  },
  {
    "heading": "Birthday Cakes For",
    "links": [
      {
        "label": "Father",
        "href": "/cakes/for-father"
      },
      {
        "label": "Mother",
        "href": "/cakes/for-mother"
      },
      {
        "label": "Kids",
        "href": "/cakes/for-kids"
      },
      {
        "label": "Wife",
        "href": "/cakes/for-wife"
      },
      {
        "label": "Husband",
        "href": "/cakes/for-husband"
      },
      {
        "label": "Friend",
        "href": "/cakes/for-friend"
      },
      {
        "label": "Her",
        "href": "/cakes/for-her"
      },
      {
        "label": "Him",
        "href": "/cakes/for-him"
      },
      {
        "label": "Brother",
        "href": "/cakes/for-brother"
      },
      {
        "label": "Sister",
        "href": "/cakes/for-sister"
      },
      {
        "label": "Boy",
        "href": "/cakes/for-boy"
      },
      {
        "label": "Girl",
        "href": "/cakes/for-girl"
      },
      {
        "label": "Boyfriend",
        "href": "/cakes/for-boyfriend"
      },
      {
        "label": "Girlfriend",
        "href": "/cakes/for-girlfriend"
      }
    ]
  },
  {
    "heading": "Theme Cakes",
    "links": [
      {
        "label": "Car",
        "href": "/designer-cakes/car-cakes"
      },
      {
        "label": "Cartoon",
        "href": "/designer-cakes/cartoon-cakes"
      },
      {
        "label": "Spiderman",
        "href": "/designer-cakes/spiderman-cakes"
      },
      {
        "label": "Doraemon",
        "href": "/designer-cakes/doraemon-cakes"
      },
      {
        "label": "Princess",
        "href": "/designer-cakes/princess-cakes"
      },
      {
        "label": "Barbie",
        "href": "/designer-cakes/barbie-cakes"
      },
      {
        "label": "Butterfly",
        "href": "/designer-cakes/butterfly-cakes"
      },
      {
        "label": "Cricket",
        "href": "/designer-cakes/cricket-cakes"
      },
      {
        "label": "Avenger",
        "href": "/designer-cakes/avenger-cakes"
      },
      {
        "label": "Cocomelon",
        "href": "/designer-cakes/cocomelon-cakes"
      },
      {
        "label": "Baby Shower",
        "href": "/designer-cakes/baby-shower-cakes"
      },
      {
        "label": "Jungle Theme",
        "href": "/designer-cakes/jungle-theme-cakes"
      },
      {
        "label": "Free Fire",
        "href": "/designer-cakes/free-fire-cakes"
      },
      {
        "label": "Number",
        "href": "/designer-cakes/number-cakes"
      },
      {
        "label": "Hello Kitty",
        "href": "/designer-cakes/hello-kitty-cakes"
      },
      {
        "label": "Football",
        "href": "/designer-cakes/football-cakes"
      },
      {
        "label": "Mickey Mouse",
        "href": "/designer-cakes/mickey-mouse-cakes"
      },
      {
        "label": "Superhero",
        "href": "/designer-cakes/superhero-cakes"
      },
      {
        "label": "Beer",
        "href": "/designer-cakes/beer-cakes"
      },
      {
        "label": "Chota Bheem",
        "href": "/designer-cakes/chota-bheem-cakes"
      },
      {
        "label": "Dinosaur",
        "href": "/designer-cakes/dinosaur-cakes"
      },
      {
        "label": "Batman",
        "href": "/designer-cakes/batman-cakes"
      }
    ]
  },
  {
    "heading": "TRENDING CAKES BY TYPE",
    "links": [
      {
        "label": "Pinata Cakes",
        "href": "/pinata-cakes"
      },
      {
        "label": "Pull Me Up Cakes",
        "href": "/pull-me-up-cakes"
      },
      {
        "label": "Half Cakes",
        "href": "/half-cakes"
      },
      {
        "label": "Party Cakes",
        "href": "/party-cakes"
      },
      {
        "label": "Cup Cakes",
        "href": "/cup-cakes"
      },
      {
        "label": "Photo Cakes",
        "href": "/photo-cakes"
      },
      {
        "label": "Jar Cakes",
        "href": "/jar-cakes"
      },
      {
        "label": "Plum Cakes",
        "href": "/plum-cakes"
      },
      {
        "label": "Eggless Cakes",
        "href": "/eggless-cakes"
      }
    ]
  },
  {
    "heading": "BEST CAKES BY FLAVOUR",
    "links": [
      {
        "label": "Chocolate Cakes",
        "href": "/chocolate-cakes"
      },
      {
        "label": "Black Forest Cakes",
        "href": "/black-forest-cakes"
      },
      {
        "label": "Butterscotch Cakes",
        "href": "/butterscotch-cakes"
      },
      {
        "label": "Red Velvet Cakes",
        "href": "/red-velvet-cakes"
      },
      {
        "label": "Vanilla Cakes",
        "href": "/vanilla-cakes"
      },
      {
        "label": "Strawberry Cakes",
        "href": "/strawberry-cakes"
      },
      {
        "label": "Pineapple Cakes",
        "href": "/pineapple-cakes"
      },
      {
        "label": "Heart Shape Cakes",
        "href": "/heart-shape-cakes"
      },
      {
        "label": "Fruit Cakes",
        "href": "/fruit-cakes"
      },
      {
        "label": "Coffee Cakes",
        "href": "/coffee-cakes"
      }
    ]
  },
  {
    "heading": "Most Celebrated",
    "links": [
      {
        "label": "Birthday Cakes",
        "href": "/birthday-cakes"
      },
      {
        "label": "First Birthday Cakes",
        "href": "/1st-birthday-cakes"
      },
      {
        "label": "Anniversary Cakes",
        "href": "/anniversary-cakes"
      },
      {
        "label": "Engagement Cakes",
        "href": "/engagement-cakes"
      },
      {
        "label": "Farewell Cakes",
        "href": "/farewell-cakes"
      },
      {
        "label": "Retirement Cakes",
        "href": "/retirement-cakes"
      }
    ]
  },
  {
    "heading": "Occasion Special Cakes",
    "links": [
      {
        "label": "Valentine's Day Cakes",
        "href": "/valentine-cakes"
      },
      {
        "label": "Mother's Day Cakes",
        "href": "/mothers-day-cakes"
      },
      {
        "label": "Father's Day Cakes",
        "href": "/fathers-day-cakes"
      },
      {
        "label": "Friendship Day Cakes",
        "href": "/friendship-day-cakes"
      },
      {
        "label": "Rakhi Cakes",
        "href": "/rakhi-with-cakes"
      },
      {
        "label": "Rakhi Gift Hampers",
        "href": "/rakhi-gift-hampers"
      },
      {
        "label": "Women's Day Cakes",
        "href": "/womens-day-cakes"
      },
      {
        "label": "Halloween Cakes",
        "href": "/halloween-cakes"
      },
      {
        "label": "Christmas Cakes",
        "href": "/christmas-cakes"
      },
      {
        "label": "New Year Cakes",
        "href": "/new-year-cakes"
      },
      {
        "label": "Teacher's Day Cakes",
        "href": "/teachers-day-cakes"
      }
    ]
  },
  {
    "heading": "Top Searches",
    "links": [
      {
        "label": "Gourmet Cakes",
        "href": "/gourmet-cakes"
      },
      {
        "label": "Designer Cakes",
        "href": "/designer-cakes"
      },
      {
        "label": "Bakery Basket",
        "href": "/bakery-baskets"
      },
      {
        "label": "Pastries",
        "href": "/pastries"
      },
      {
        "label": "Bento Cakes",
        "href": "/bento-cakes"
      },
      {
        "label": "Labubu Cakes",
        "href": "/designer-cakes/labubu-cakes"
      }
    ]
  }
];
