/**
 * India Loves bestseller cards.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-data.mjs.
 */
import type { ProductCard, SectionHeading } from "@/types/bakingo";

export const bestsellers: ProductCard[] = [
  {
    "name": "Rich Chocolate Truffle Cake",
    "href": "/p/cake/choco-truffle-cake0005choc",
    "image": "/images/choco-truffle-cake0005choc-aa.jpg",
    "alt": "Rich Chocolate Truffle Cake",
    "price": "₹549",
    "rating": "4.9",
    "reviews": "8.8K",
    "eggless": true
  },
  {
    "name": "Tropical Fruit n Almond Cake",
    "href": "/p/cake/fresh-fruit-cake0014frui",
    "image": "/images/fresh-fruit-cake0014fruit-a.jpg",
    "alt": "Tropical Fruit n Almond Cake",
    "price": "₹649",
    "rating": "4.9",
    "reviews": "2.4K",
    "eggless": true
  },
  {
    "name": "Butterscotch Crunch Cake",
    "href": "/p/cake/butterscotch-crunch-cake-cake5911butt",
    "image": "/images/butterscotch-crunch-cake-cake5911butt-aa.jpg",
    "alt": "Butterscotch Crunch Cake",
    "price": "₹529",
    "rating": "5",
    "reviews": "31",
    "eggless": true
  },
  {
    "name": "Whipped Cream Pineapple Cake",
    "href": "/p/cake/pineapple-cake0022pifr",
    "image": "/images/sq-pineapple-cake0022pifr-aaaa.jpg",
    "alt": "Whipped Cream Pineapple Cake",
    "price": "₹549",
    "rating": "4.9",
    "reviews": "1.8K",
    "eggless": true
  },
  {
    "name": "Choco Chip Truffle Cake",
    "href": "/p/cake/chocolate-chip-cake0008choc",
    "image": "/images/chocolate-chip-cake0008choc-aaaa.jpg",
    "alt": "Choco Chip Truffle Cake",
    "price": "₹549",
    "rating": "4.9",
    "reviews": "1.6K",
    "eggless": true
  },
  {
    "name": "Rose Petals N Pistachio Rasmalai Cake",
    "href": "/p/cake/pista-topped-rasmalai-cake-cake3550rash",
    "image": "/images/pista-topped-rasmalai-cake-cake3550rash-aa.jpg",
    "alt": "Rose Petals N Pistachio Rasmalai Cake",
    "price": "₹699",
    "rating": "4.8",
    "reviews": "596",
    "eggless": true
  },
  {
    "name": "Chocolate Vanilla Half & Half Cake",
    "href": "/p/cake/choco-vanilla-cake0006chva",
    "image": "/images/choco-vanilla-cake0006chva-aaaaa_0.jpg",
    "alt": "Chocolate Vanilla Half & Half Cake",
    "price": "₹549",
    "rating": "4.9",
    "reviews": "3.1K",
    "eggless": true
  },
  {
    "name": "Roll Up Chocolate Truffle Cake",
    "href": "/p/cake/round-shaped-chocolate-cake-1-cake0653choc",
    "image": "/images/sq-round-shaped-chocolate-cake-1-cake0653choc-aa.jpg",
    "alt": "Roll Up Chocolate Truffle Cake",
    "price": "₹549",
    "rating": "4.9",
    "reviews": "1.5K",
    "eggless": true
  },
  {
    "name": "Blueberry Cheesecake",
    "href": "/p/cake/viscous-blueberry-cheesecake-cake2859blue",
    "image": "/images/viscous-blueberry-cheesecake-cake2859blue-aaa.jpg",
    "alt": "Blueberry Cheesecake",
    "price": "₹779",
    "rating": "4.9",
    "reviews": "831",
    "eggless": true
  },
  {
    "name": "Classic Black Forest Cake",
    "href": "/p/cake/black-forest-cake0001chbl",
    "image": "/images/black-forest-cake0001chbl-aaaa1-jpg.jpg",
    "alt": "Classic Black Forest Cake",
    "price": "₹549",
    "rating": "4.9",
    "reviews": "1.0K",
    "eggless": true
  },
  {
    "name": "Choco Truffle Cake made With KitKat",
    "href": "/p/cake/kitkat-chocolate-cake-cake1119choco",
    "image": "/images/kitkat-chocolate-cake-cake1119choco-aaa-jpg.jpg",
    "alt": "Choco Truffle Cake made With KitKat",
    "price": "₹649",
    "rating": "4.9",
    "reviews": "1.0K",
    "eggless": true
  },
  {
    "name": "Belgian Chocolate Cake",
    "href": "/p/cake/belgium-chocolate-mousse-cake-cake3217beli",
    "image": "/images/belgium-chocolate-mousse-cake-cake3217beli-cccc.jpg",
    "alt": "Belgian Chocolate Cake",
    "price": "₹649",
    "rating": "4.9",
    "reviews": "588",
    "eggless": true
  },
  {
    "name": "Chocolate Ganache Truffle Cake",
    "href": "/p/cake/round-shaped-chocolate-cake-2-cake0654choc",
    "image": "/images/sq-round-shaped-chocolate-cake-2-cake0654choc-aa_0.jpg",
    "alt": "Chocolate Ganache Truffle Cake",
    "price": "₹549",
    "rating": "4.9",
    "reviews": "939",
    "eggless": true
  },
  {
    "name": "Rosy Petals Heart Cake",
    "href": "/p/theme-cake/rosy-petals-valentines-heart-cake-them5739flav",
    "image": "/images/rosy-petals-valentines-heart-cake-them5739flav-a.jpg",
    "alt": "Rosy Petals Heart Cake",
    "price": "₹749",
    "rating": "5",
    "reviews": "116",
    "eggless": true
  },
  {
    "name": "Choco Dream Cake",
    "href": "/p/cake/chocolate-dream-cake-cake3750drea",
    "image": "/images/chocolate-dream-cake-cake3750drea-aaa.jpg",
    "alt": "Choco Dream Cake",
    "price": "₹649",
    "rating": "4.9",
    "reviews": "1.0K",
    "eggless": true
  },
  {
    "name": "Red Velvet Heart Shape Cake",
    "href": "/p/cake/heart-shaped-red-velvet-cake-cake1095redv",
    "image": "/images/heart-shaped-red-velvet-cake-cake1095redv-a.jpg",
    "alt": "Red Velvet Heart Shape Cake",
    "price": "₹799",
    "rating": "4.9",
    "reviews": "314",
    "eggless": true
  },
  {
    "name": "Roses Topped Vanilla Cream Cake",
    "href": "/p/cake/round-pink-roses-vanilla-cake-rosecake2561vani",
    "image": "/images/sq-round-pink-roses-vanilla-cake-rosecake2561vani-aaaa_0.jpg",
    "alt": "Roses Topped Vanilla Cream Cake",
    "price": "₹1149",
    "rating": "4.9",
    "reviews": "253",
    "eggless": true
  },
  {
    "name": "Velvet Chocolate Truffle Cake",
    "href": "/p/cake/lip-smacking-chocolate-truffle-cake-cake2161choc",
    "image": "/images/sq-lip-smacking-chocolate-truffle-cake-cake2161choc-aaaa.jpg",
    "alt": "Velvet Chocolate Truffle Cake",
    "price": "₹549",
    "rating": "4.9",
    "reviews": "524",
    "eggless": true
  },
  {
    "name": "German Black Forest Cake",
    "href": "/p/cake/choco-black-forest-cake-cake888blac",
    "image": "/images/squ-choco-black-forest-cake-cake888blac-aaaa.jpg",
    "alt": "German Black Forest Cake",
    "price": "₹559",
    "rating": "4.9",
    "reviews": "284",
    "eggless": true
  },
  {
    "name": "Pink Princess Barbie Cake",
    "href": "/p/theme-cake/fantasy-barbie-cake-them2655flav",
    "image": "/images/fantasy-barbie-cake-bg-them2655flav-a_0.jpg",
    "alt": "Pink Princess Barbie Cake",
    "price": "₹1479",
    "rating": "4.9",
    "reviews": "243",
    "eggless": true
  }
];

export const bestsellersHeading: SectionHeading = {
  "eyebrow": "india loves",
  "subtitle": "Bestsellers from across the country"
};
