/**
 * Our Promise columns.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-data.mjs.
 */
import type { PromiseItem, SectionHeading } from "@/types/bakingo";

export const promiseItems: PromiseItem[] = [
  {
    "image": "/images/on-time-delivery_0.png",
    "alt": "On Time Delivery",
    "title": "ON-TIME DELIVERY",
    "body": "Because no one likes late surprises."
  },
  {
    "image": "/images/promise-design_0.png",
    "alt": "On Time Delivery",
    "title": "500+ DESIGNS",
    "body": "Wishes come in all shapes and sizes."
  },
  {
    "image": "/images/promise-order_0.png",
    "alt": "On Time Delivery",
    "title": "2 CR+ ORDERS",
    "body": "You can close your eyes and trust us."
  },
  {
    "image": "/images/promise-baked_0.png",
    "alt": "On Time Delivery",
    "title": "BAKED FRESH",
    "body": "Spreading smiles, one slice at a time."
  }
];

export const promiseHeading: SectionHeading = {
  "eyebrow": "our promise",
  "subtitle": "There’s no secret spell—only honest, hard work!"
};
