/**
 * SEO sub-footer links + copy.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-data.mjs.
 */
import type { SeoLink } from "@/types/bakingo";

export const seoLinks: SeoLink[] = [
  {
    "label": "Red Velvet",
    "href": "https://www.bakingo.com/red-velvet-cakes"
  },
  {
    "label": "Butterscotch",
    "href": "https://www.bakingo.com/butterscotch-cakes"
  },
  {
    "label": "Strawberry",
    "href": "https://www.bakingo.com/strawberry-cakes"
  },
  {
    "label": "Chocolate",
    "href": "https://www.bakingo.com/chocolate-cakes"
  },
  {
    "label": "Vanilla",
    "href": "https://www.bakingo.com/vanilla-cakes"
  },
  {
    "label": "Blueberry",
    "href": "https://www.bakingo.com/blueberry-cakes"
  },
  {
    "label": "Pineapple",
    "href": "https://www.bakingo.com/pineapple-cakes"
  },
  {
    "label": "Coffee",
    "href": "https://www.bakingo.com/coffee-cakes"
  },
  {
    "label": "Mango",
    "href": "https://www.bakingo.com/mango-cakes"
  },
  {
    "label": "Ferrero Rocher",
    "href": "https://www.bakingo.com/ferrero-rocher-cakes"
  },
  {
    "label": "Kit-kat",
    "href": "https://www.bakingo.com/kit-kat-cakes"
  },
  {
    "label": "Oreo",
    "href": "https://www.bakingo.com/p/cake/oreo-chocolate-cake0021chex"
  },
  {
    "label": "brownies",
    "href": "https://www.bakingo.com/brownies"
  },
  {
    "label": "cupcakes",
    "href": "https://www.bakingo.com/cup-cakes"
  },
  {
    "label": "jar cakes",
    "href": "https://www.bakingo.com/jar-cakes"
  },
  {
    "label": "Pastries",
    "href": "https://www.bakingo.com/pastries"
  },
  {
    "label": "cookies",
    "href": "https://www.bakingo.com/cookies"
  },
  {
    "label": "birthday cakes",
    "href": "https://www.bakingo.com/birthday-cakes"
  },
  {
    "label": "anniversary cakes",
    "href": "https://www.bakingo.com/anniversary-cakes"
  },
  {
    "label": "Rakhi cakes",
    "href": "https://www.bakingo.com/rakhi-with-cakes"
  },
  {
    "label": "Teacher’s Day cakes",
    "href": "https://www.bakingo.com/teachers-day-cakes"
  },
  {
    "label": "Ganesh Chaturthi cakes",
    "href": "https://www.bakingo.com/ganesh-chaturthi-cakes"
  },
  {
    "label": "https://www.bakingo.com/cancellation-and-refund-policy",
    "href": "https://www.bakingo.com/cancellation-and-refund-policy"
  },
  {
    "label": "Delhi",
    "href": "https://www.bakingo.com/cakes/delhi"
  },
  {
    "label": "Bangalore",
    "href": "https://www.bakingo.com/cakes/bangalore"
  },
  {
    "label": "Gurgaon",
    "href": "https://www.bakingo.com/cakes/gurgaon"
  },
  {
    "label": "Noida",
    "href": "https://www.bakingo.com/cakes/noida"
  },
  {
    "label": "Mumbai",
    "href": "https://www.bakingo.com/cakes/mumbai"
  },
  {
    "label": "Pune",
    "href": "https://www.bakingo.com/cakes/pune"
  },
  {
    "label": "Ghaziabad",
    "href": "https://www.bakingo.com/cakes/ghaziabad"
  },
  {
    "label": "Chennai",
    "href": "https://www.bakingo.com/cakes/chennai"
  },
  {
    "label": "Hyderabad",
    "href": "https://www.bakingo.com/cakes/hyderabad"
  },
  {
    "label": "Secunderabad",
    "href": "https://www.bakingo.com/cakes/secunderabad"
  },
  {
    "label": "Kolkata",
    "href": "https://www.bakingo.com/cakes/kolkata"
  },
  {
    "label": "Coimbatore",
    "href": "https://www.bakingo.com/cakes/coimbatore"
  },
  {
    "label": "Kanpur",
    "href": "https://www.bakingo.com/cakes/kanpur"
  },
  {
    "label": "Jaipur",
    "href": "https://www.bakingo.com/cakes/jaipur"
  },
  {
    "label": "Jalandhar",
    "href": "https://www.bakingo.com/cakes/jalandhar"
  },
  {
    "label": "Faridabad",
    "href": "https://www.bakingo.com/cakes/faridabad"
  },
  {
    "label": "Patna",
    "href": "https://www.bakingo.com/cakes/patna"
  },
  {
    "label": "Ranchi",
    "href": "https://www.bakingo.com/cakes/ranchi"
  },
  {
    "label": "Ludhiana",
    "href": "https://www.bakingo.com/cakes/ludhiana"
  },
  {
    "label": "Ahmedabad",
    "href": "https://www.bakingo.com/cakes/ahmedabad"
  },
  {
    "label": "Amritsar",
    "href": "https://www.bakingo.com/cakes/amritsar"
  },
  {
    "label": "Lucknow",
    "href": "https://www.bakingo.com/cakes/lucknow"
  },
  {
    "label": "Dehradun",
    "href": "https://www.bakingo.com/cakes/dehradun"
  },
  {
    "label": "Haridwar",
    "href": "https://www.bakingo.com/cakes/haridwar"
  },
  {
    "label": "Surat",
    "href": "https://www.bakingo.com/cakes/surat"
  },
  {
    "label": "Chandigarh",
    "href": "https://www.bakingo.com/cakes/chandigarh"
  },
  {
    "label": "Mohali",
    "href": "https://www.bakingo.com/cakes/mohali"
  },
  {
    "label": "Panchkula",
    "href": "https://www.bakingo.com/cakes/panchkula"
  }
];

export const seoHeading: string = "Bakingo - Your Trusted FSSAI Certified Online Bakery for Every Celebration";

export const seoParagraphs: string[] = [
  "We are exactly what you are looking for. Yes, we are an FSSAI certified online cake and Bakery Company that specializes in delivering absolutely lip-smacking delicacies. Currently, we are delivering cakes in Gurgaon, Delhi, Noida, Ghaziabad, Bangalore, Hyderabad, Mumbai, Kolkata, Chennai, and many other cities. We are here to create some unforgettable memories and some undying emotions by helping you to send cake online to your beloved ones.",
  "Our mission is to “deliver these heavenly cakes at your doorstep on time to make your celebrations even grander”. Because for us, it is not just a Cake but more and so we craft it with a blend of inspiration, passion, and love. We guarantee an extraordinary taste in your choicest flavors with ravishing designs. Sounds perfect, isn’t it?",
  "So, be prepared to experience something devilishly delicious, something that will take even the hardest to please Cake Lovers on a delectable ride into the World of Sweet Indulgence where we celebrate Happiness! Watch Out Us! We are Bakingo, a brand you will call the best cake shop near me after having our cakes. We Are Here to Redefine Sweetness & our matchless services of delivering cakes online.",
  "Now, having a birthday , anniversary or wedding cake is completely a hassle-free task with Bakingo. Earlier, you would have to go from one shop to another in search for a delectable cake to heighten the happiness of your special occasions. But now, with Bakingo’s online cake delivery, you can browse through a variety of best quality cakes and pick your favorite cake just sitting at your home. After you have selected your favorite cake from our varieties, order the cake online in a few clicks and relax because Bakingo ensure same day cake delivery. Yes, now gorge on your favorite delicacies and take your special occasions to new heights with Bakingo’s online cake delivery service. With our melt-in-mouth delicacies now you can also deliver your heartfelt wishes and affection to your loved ones on their special days. In fact, even if you live in another country and wants to send a delicious cake to India for your parents, relatives, or friends on their birthday, anniversary or any other occasion, then you can completely count on Bakingo for timely delivery because we understand your love and emotions towards your close ones. So, go ahead and place your online cake order from us from your comfort, and we will serve you the perfectly baked delicacies. Our online cake delivery service promise to deliver on the same day.",
  "Bakingo’s online cake delivery offers you a huge range of cakes baked with utmost perfection and the finest quality of ingredients. Cakes available in our bakery are always fresh, soft, moist, mushy and fluffy in texture. We have flavorsome cakes to illuminate your every occasion. Be it a birthday, wedding, anniversary, Valentine's day, Mother's day or any other event, our cakes will never disappoint you. These hard-to-resist delicacies are available in a plethora of flavors like Red Velvet, Butterscotch, Strawberry, Chocolate, Vanilla, Blueberry, Pineapple, Coffee, Mango, Ferrero Rocher, Kit-kat, Oreo and many more. Since no one can say ‘No’ to chocolates, we have come up with a variety of chocolate cakes among which 'Double-Trouble', 'Alive by Chocolate' and Rocher Rejoice with just leave your mouth water. If you are a fruit lover, then you must try our extremely delicious Red Velvet fruit cake enriched with fruits and adorned with whipped cream. With Bakingo, you can proudly say that \"I have the best cakes near me' which will be at your doorstep within a few clicks.So, if there is a huge celebration waiting up next in your calendar, order a cake online from us and brighten up your celebration with our irresistible yummylicious treats. Our online cake delivery service promise to deliver on the same day.",
  "From rich cakes to crispy cookies, Bakingo presents a wide array of freshly baked desserts online.",
  "Cakes – Soft, moist, and full of savour, our cakes are perfect for celebrating special moments or enjoying a treat. We bake each cake fresh, offering a variety of flavours and designs.",
  "Brownies – Our brownies are the perfect treat to enjoy anytime. They are rich, chocolatey, and just the right amount of fudgy. You can share them with friends or enjoy one alone with a cup of coffee.",
  "Cupcakes – Our cupcakes are nothing but mini cakes packed with a punch of flavours. Decorated with care, they’re perfect for parties, gifting, or just a little indulgence whenever you want.",
  "Jar Cakes – These are fun, single-serve cakes in jars. They are easy to carry and enjoyable to eat. Our jar cakes make great individual treats or a perfect little surprise for someone special.",
  "Pastries – An indulgent sweet treat known for their light and flaky texture, layered with delicious fillings. Pastries are a delightful treat, ideal for breakfast, tea time, or as a quick snack.",
  "Cookies – Our cookies are crunchy, buttery, and full of flavour. They are freshly baked and available in a variety of flavours. A perfect treat for nibbling anytime or gifting in a charming box.",
  "No matter the event, Bakingo has the perfect cakes to make your moments even more special. Our range of delicious cakes is designed to sweeten any celebration and leave a lasting impression. With a wide variety of options available, you're sure to find the perfect cake to match your occasion. Whether you are looking for birthday cakes for your loved ones or romantic anniversary cakes for your love milestones, we have got you covered.",
  "The coming months are packed with heartfelt celebrations, and Bakingo has the perfect cakes to match every emotion and occasion. Celebrate the bond of protection and love with our delightful Rakhi cakes, crafted to make Raksha Bandhan extra sweet. Honour your favourite mentors with thoughtfully designed Teacher’s Day cakes that say thank you in the most delicious way. As the festive season begins, welcome Bappa home with auspicious Ganesh Chaturthi cakes that add sweetness to the celebrations. And to make your little girl feel cherished, our charming are the perfect way to celebrate her special day. From classic chocolate flavours to trendy designer creations, Bakingo brings freshly baked cakes for every celebration right to your doorstep. Order online and turn every upcoming occasion into a flavour-filled memory worth cherishing.",
  "Bifurcating things furthermore means providing ease of selection, and that’s what Bakingo do through various types of cake delivery services. When you order cake online from Bakingo, you get the luxury to choose from delivery types as per your comfort and convenience. There can be situations where you want the cake at a fixed time to enhance the surprise, and so you can opt for a fixed time cake delivery service for which you have to pay Rs. 150/- only. Some people would love to celebrate over cakes early in the morning, and thus we serve them our delicacies through early morning delivery at a delivery charge of Rs. 150/- only. The excitement of surprise and the fun doubles when it is given at midnight. So, if you plan to flabbergast someone with a cake at 12 AM, you can opt-out midnight cake delivery, for which we charge Rs. 250/- only. You can also place cake orders online for same-day delivery and 2-hour delivery, and we provide the delivery service for free.",
  "Delhi | Bangalore | Gurgaon | Noida | Mumbai | Pune | Ghaziabad | Chennai | Hyderabad | Secunderabad | Kolkata | Coimbatore | Kanpur | Jaipur | Jalandhar | Faridabad | Patna | Ranchi | Ludhiana | Ahmedabad | Amritsar | Lucknow | Dehradun | Haridwar | Surat | Chandigarh | Mohali | Panchkula"
];
