/**
 * What's In Your Heart social tiles.
 * Extracted verbatim from https://www.bakingo.com/ — generated by scripts/generate-data.mjs.
 */
import type { SocialTile, SectionHeading } from "@/types/bakingo";

export const socialRows: SocialTile[][] = [
  [
    {
      "image": "/images/instagram/772264744_18438874738135913_6284807406954571232_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/771708465_18438544915135913_5711236691178066779_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/767335440_18438363898135913_7058279990008766779_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/764986785_18437962081135913_5272848799090819017_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/763051251_18437532076135913_8537643987186050976_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/761719383_18437367346135913_4530366959654491292_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/758423461_18437172637135913_6528176987411111876_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/758481175_18437038456135913_6156344412907259162_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/758377242_18436821004135913_6750938682657119652_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/756894709_18436665775135913_4095723386414195425_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/754143172_18436401592135913_191899295826718569_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/755246254_18435995830135913_8528620791607820274_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/754069846_18435569275135913_323320280062698369_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/751798878_18435369019135913_1449097865769901246_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/749010565_18435025921135913_5478218584440561847_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/748243223_18434680696135913_1878202659384266933_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/743425387_18434257051135913_1978684489582562296_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/746791387_18434113051135913_6628892013965616165_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/743842366_18433722673135913_1775163804365691059_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/742787263_18433404028135913_8282049005696203949_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/731623679_18433105507135913_680913555127437921_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/731324686_18432679213135913_8556584085242048135_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/733892037_1013847097951052_6149763177682453632_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/729692130_18432155092135913_5138177502739929764_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/728950873_18431869498135913_1876521315416229007_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/729623454_18431259709135913_794304674757724527_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/728180851_18430921903135913_2795887274687738497_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/728247053_18430803496135913_2285652918231830393_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/728580804_18430230928135913_6853994875171603943_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/726531469_18430059022135913_8479065283592974448_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/727303279_18429941098135913_3789709297219390559_n.jpg",
      "alt": "",
      "width": 235,
      "height": 293
    },
    {
      "image": "/images/instagram/725133117_18429890749135913_9033016400327941536_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/726405370_1027000469745004_6595557039399087595_n.jpg",
      "alt": "",
      "width": 521,
      "height": 293
    },
    {
      "image": "/images/instagram/725198828_18429616984135913_2893320983721769613_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/723238619_18429447493135913_5499382700399769343_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/723066403_2140698743174589_463520017076813166_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/731764037_18433105825135913_9000012600494010487_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/721430155_1575422544242048_5264772803859550624_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/718538849_2281755769308482_682064790708754821_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/716762752_4391697384490022_3030226676306929321_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/715375796_18427764094135913_8889055724864838630_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/708852881_1010206524786721_3757328585967264698_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/708967745_18426988249135913_7078159414040396615_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/707248019_962518896395638_2514710119405317116_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/706919115_18426200290135913_3093672450028096863_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    }
  ],
  [
    {
      "image": "/images/instagram/703954403_1720293188972425_70717891240389780_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/705214095_18425551177135913_7668854261326520105_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/703449031_2496589577478189_4076694449160678781_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/689393810_18425097895135913_1466363609324443601_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/701409369_18424871674135913_6608076924497668084_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/670727573_18424750321135913_9031725572354596316_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/687127123_18423696322135913_3326387316330470403_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/684702795_18423548497135913_1487648238890835087_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/684486870_938202255697545_8762270143962589518_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instreel-f142e55b.svg",
      "alt": "Instagram Reel",
      "width": 24,
      "height": 24
    },
    {
      "image": "/images/instagram/686495387_1353759566723833_8941944692066702329_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/684696858_18423214021135913_7256077333793845721_n.jpg",
      "alt": "",
      "width": 220,
      "height": 293
    },
    {
      "image": "/images/instagram/683612818_18422526817135913_2419720392297654876_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/682885000_18422355877135913_3436889974266498782_n.jpg",
      "alt": "",
      "width": 293,
      "height": 293
    },
    {
      "image": "/images/instagram/684123068_945603671603767_5896067595954204543_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/673832001_18421751491135913_4145577120300916705_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/672366702_1739949880305925_6286554736283132500_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/672341486_18421271614135913_7264867468245962072_n.jpg",
      "alt": "",
      "width": 293,
      "height": 293
    },
    {
      "image": "/images/instagram/670634341_1283553716506020_5960895735571988506_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/670309342_18420641818135913_7958054560369052331_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/671169006_947911960976471_2609260883201784362_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/669752226_1591517698817017_1195939211495144741_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/670841242_4332503333563143_5980534086919581422_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/670055812_1451880103070674_1593244963351574728_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/662108070_800907209741665_3725289015231296279_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/658797188_2758443661171625_3836722310058292637_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/659036917_26095543360145818_8161301264214660302_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/656726696_18417881911135913_126749913374934742_n.jpg",
      "alt": "",
      "width": 220,
      "height": 293
    },
    {
      "image": "/images/instagram/657177486_18417702409135913_809215272368154221_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/656197752_1652590929228138_8751635097064406474_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/658925992_18417159370135913_2761341263677432197_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/657912912_928286713265631_1995927662712536444_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/658160516_18416452177135913_5841857888137941622_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/657719721_18416268322135913_3153135488919318724_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/656462020_1213542603910417_5859805839625890704_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/655229115_1303780571804137_1630427245649766641_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/651506202_920782350596460_1386990994908338870_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/653562847_18414363433135913_1928416653367536174_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/648743731_1432549294916100_4995646404176826079_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/642960666_18413250757135913_8413221284829113920_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/650021091_18413541574135913_3109690397288754130_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    },
    {
      "image": "/images/instagram/642946404_18412934179135913_1712351900510858615_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/640389539_18412803484135913_7559204981395675416_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/641767716_18412621837135913_8490188864435597115_n.jpg",
      "alt": "",
      "width": 234,
      "height": 293
    },
    {
      "image": "/images/instagram/640411540_1235603364840185_8037592951465172408_n.jpg",
      "alt": "",
      "width": 165,
      "height": 293
    }
  ]
];

export const socialTiles: SocialTile[] = [
  {
    "image": "/images/instagram/772264744_18438874738135913_6284807406954571232_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/771708465_18438544915135913_5711236691178066779_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/767335440_18438363898135913_7058279990008766779_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/764986785_18437962081135913_5272848799090819017_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/763051251_18437532076135913_8537643987186050976_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/761719383_18437367346135913_4530366959654491292_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/758423461_18437172637135913_6528176987411111876_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/758481175_18437038456135913_6156344412907259162_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/758377242_18436821004135913_6750938682657119652_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/756894709_18436665775135913_4095723386414195425_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/754143172_18436401592135913_191899295826718569_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/755246254_18435995830135913_8528620791607820274_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/754069846_18435569275135913_323320280062698369_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/751798878_18435369019135913_1449097865769901246_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/749010565_18435025921135913_5478218584440561847_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/748243223_18434680696135913_1878202659384266933_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/743425387_18434257051135913_1978684489582562296_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/746791387_18434113051135913_6628892013965616165_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/743842366_18433722673135913_1775163804365691059_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/742787263_18433404028135913_8282049005696203949_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/731623679_18433105507135913_680913555127437921_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/731324686_18432679213135913_8556584085242048135_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/733892037_1013847097951052_6149763177682453632_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/729692130_18432155092135913_5138177502739929764_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/728950873_18431869498135913_1876521315416229007_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/729623454_18431259709135913_794304674757724527_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/728180851_18430921903135913_2795887274687738497_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/728247053_18430803496135913_2285652918231830393_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/728580804_18430230928135913_6853994875171603943_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/726531469_18430059022135913_8479065283592974448_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/727303279_18429941098135913_3789709297219390559_n.jpg",
    "alt": "",
    "width": 235,
    "height": 293
  },
  {
    "image": "/images/instagram/725133117_18429890749135913_9033016400327941536_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/726405370_1027000469745004_6595557039399087595_n.jpg",
    "alt": "",
    "width": 521,
    "height": 293
  },
  {
    "image": "/images/instagram/725198828_18429616984135913_2893320983721769613_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/723238619_18429447493135913_5499382700399769343_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/723066403_2140698743174589_463520017076813166_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/731764037_18433105825135913_9000012600494010487_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/721430155_1575422544242048_5264772803859550624_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/718538849_2281755769308482_682064790708754821_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/716762752_4391697384490022_3030226676306929321_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/715375796_18427764094135913_8889055724864838630_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/708852881_1010206524786721_3757328585967264698_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/708967745_18426988249135913_7078159414040396615_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/707248019_962518896395638_2514710119405317116_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/706919115_18426200290135913_3093672450028096863_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/703954403_1720293188972425_70717891240389780_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/705214095_18425551177135913_7668854261326520105_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/703449031_2496589577478189_4076694449160678781_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/689393810_18425097895135913_1466363609324443601_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/701409369_18424871674135913_6608076924497668084_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/670727573_18424750321135913_9031725572354596316_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/687127123_18423696322135913_3326387316330470403_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/684702795_18423548497135913_1487648238890835087_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/684486870_938202255697545_8762270143962589518_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instreel-f142e55b.svg",
    "alt": "Instagram Reel",
    "width": 24,
    "height": 24
  },
  {
    "image": "/images/instagram/686495387_1353759566723833_8941944692066702329_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/684696858_18423214021135913_7256077333793845721_n.jpg",
    "alt": "",
    "width": 220,
    "height": 293
  },
  {
    "image": "/images/instagram/683612818_18422526817135913_2419720392297654876_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/682885000_18422355877135913_3436889974266498782_n.jpg",
    "alt": "",
    "width": 293,
    "height": 293
  },
  {
    "image": "/images/instagram/684123068_945603671603767_5896067595954204543_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/673832001_18421751491135913_4145577120300916705_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/672366702_1739949880305925_6286554736283132500_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/672341486_18421271614135913_7264867468245962072_n.jpg",
    "alt": "",
    "width": 293,
    "height": 293
  },
  {
    "image": "/images/instagram/670634341_1283553716506020_5960895735571988506_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/670309342_18420641818135913_7958054560369052331_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/671169006_947911960976471_2609260883201784362_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/669752226_1591517698817017_1195939211495144741_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/670841242_4332503333563143_5980534086919581422_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/670055812_1451880103070674_1593244963351574728_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/662108070_800907209741665_3725289015231296279_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/658797188_2758443661171625_3836722310058292637_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/659036917_26095543360145818_8161301264214660302_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/656726696_18417881911135913_126749913374934742_n.jpg",
    "alt": "",
    "width": 220,
    "height": 293
  },
  {
    "image": "/images/instagram/657177486_18417702409135913_809215272368154221_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/656197752_1652590929228138_8751635097064406474_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/658925992_18417159370135913_2761341263677432197_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/657912912_928286713265631_1995927662712536444_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/658160516_18416452177135913_5841857888137941622_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/657719721_18416268322135913_3153135488919318724_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/656462020_1213542603910417_5859805839625890704_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/655229115_1303780571804137_1630427245649766641_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/651506202_920782350596460_1386990994908338870_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/653562847_18414363433135913_1928416653367536174_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/648743731_1432549294916100_4995646404176826079_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/642960666_18413250757135913_8413221284829113920_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/650021091_18413541574135913_3109690397288754130_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  },
  {
    "image": "/images/instagram/642946404_18412934179135913_1712351900510858615_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/640389539_18412803484135913_7559204981395675416_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/641767716_18412621837135913_8490188864435597115_n.jpg",
    "alt": "",
    "width": 234,
    "height": 293
  },
  {
    "image": "/images/instagram/640411540_1235603364840185_8037592951465172408_n.jpg",
    "alt": "",
    "width": 165,
    "height": 293
  }
];

export const socialHeading: SectionHeading = {
  "eyebrow": "What’s In Your Heart?",
  "subtitle": "A glimpse from our social world!"
};
